POST http://localhost:8080/events
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NDkwMTU4ODYsInVzZXJJZCI6MX0.c2bDi1awLVE6tDjcxuSklE6d9dY_hXhCQSov39ORV9k

{
  "name":"Test a second Event",
  "description":"A test event",
  "location":"A test location",
  "dateTime":"2025-01-01T15:30:00.000Z"
}
