POST http://localhost:8080/events
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ5MDE0MjY0LCJ1c2VySWQiOjJ9.dz1LFkJaFQ-pDK-lRShUwTh8KwoJUCOzL5FoWBUB8Mk

{
  "name":"Test a second Event",
  "description":"A test event",
  "location":"A test location",
  "dateTime":"2025-01-01T15:30:00.000Z"
}
