POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ5MDE1OTgzLCJ1c2VySWQiOjJ9.O-atj9VV0L6FM1MEvS1UpseuiZmn-2uANNJ0k0o3tvk

